---
pipeline:
  sanity-test:
    image: python:3
    commands:
      - pip3 install requests
      - python3 sanity_check.py
  optimize-icons:
    image: alpine
    commands:
      - apk add imagemagick
      - ./build_icons.sh
  push-optimized-images:
    image: appleboy/drone-git-push
    settings:
      branch: "${CI_COMMIT_SOURCE_BRANCH}"
      commit: true
      commit_message: "[skip ci] Optimize icons"
      author_name: AcrylicIconPackBot
      ssh_key:
        from_secret: git_push_key
