---
pipeline:
  generate-iconpack:
    image: alpine
    commands:
      - ./scripts/generate_iconpack.sh
  optimize-icons:
    image: alpine
    commands:
      - apk add imagemagick
      - ./scripts/optimize_icons.sh
  push-generated-data:
    image: appleboy/drone-git-push
    settings:
      branch: "${CI_COMMIT_BRANCH}"
      remote: "git@codeberg.org:${CI_REPO}"
      commit: true
      commit_message: "[skip ci] Ran scripts"
      ssh_key:
        from_secret: git_push_key
  sanity-check:
    image: python:3
    commands:
      - pip3 install requests
      - python3 sanity_check.py
  version-check:
    image: alpine
    commands:
      - apk add bash curl jq
      - bash version_check.sh
